//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.03 at 09:52:51 AM MESZ 
//


package net.opengis.gml.v_3_1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom;
import org.jvnet.jaxb2_commons.lang.MergeStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BoundingBoxType1", propOrder = {
    "coord1",
    "coord2"
})
public class BoundingBoxType1 implements Cloneable, CopyTo, Equals, HashCode, MergeFrom, ToString
{

    @XmlElement(name = "Coord", namespace = "http://www.opengis.net/gml")
    protected CoordType coord1;
    public CoordType getCoord1() {
		return coord1;
	}

	public void setCoord1(CoordType coord1) {
		this.coord1 = coord1;
	}

	public CoordType getCoord2() {
		return coord2;
	}

	public void setCoord2(CoordType coord2) {
		this.coord2 = coord2;
	}

	@XmlElement(name = "Coord", namespace = "http://www.opengis.net/gml")
    protected CoordType coord2;

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof BoundingBoxType1)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final BoundingBoxType1 that = ((BoundingBoxType1) object);
        {
            CoordType lhsLowerCorner;
            lhsLowerCorner = this.getCoord1();
            CoordType rhsLowerCorner;
            rhsLowerCorner = that.getCoord1();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "coord1", lhsLowerCorner), LocatorUtils.property(thatLocator, "coord1", rhsLowerCorner), lhsLowerCorner, rhsLowerCorner)) {
                return false;
            }
        }
        {
        	CoordType lhsUpperCorner;
            lhsUpperCorner = this.getCoord2();
            CoordType rhsUpperCorner;
            rhsUpperCorner = that.getCoord2();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "coord2", lhsUpperCorner), LocatorUtils.property(thatLocator, "coord2", rhsUpperCorner), lhsUpperCorner, rhsUpperCorner)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            CoordType theLowerCorner;
            theLowerCorner = this.getCoord1();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "coord1", theLowerCorner), currentHashCode, theLowerCorner);
        }
        {
        	CoordType theUpperCorner;
            theUpperCorner = this.getCoord2();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "coord2", theUpperCorner), currentHashCode, theUpperCorner);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof BoundingBoxType1) {
            final BoundingBoxType1 copy = ((BoundingBoxType1) draftCopy);
            if (this.coord1!= null) {
            	CoordType sourcePOIAttributeList;
                sourcePOIAttributeList = this.getCoord1();
                CoordType copyPOIAttributeList = ((CoordType) strategy.copy(LocatorUtils.property(locator, "coord1", sourcePOIAttributeList), sourcePOIAttributeList));
                copy.setCoord1(copyPOIAttributeList);
            } else {
                copy.coord1 = null;
            }
            
            if (this.coord2!= null) {
            	CoordType sourcePOIAttributeList;
                sourcePOIAttributeList = this.getCoord2();
                CoordType copyPOIAttributeList = ((CoordType) strategy.copy(LocatorUtils.property(locator, "coord2", sourcePOIAttributeList), sourcePOIAttributeList));
                copy.setCoord1(copyPOIAttributeList);
            } else {
                copy.coord2 = null;
            }
            
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new BoundingBoxType1();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy strategy) {
        if (right instanceof BoundingBoxType1) {
            final BoundingBoxType1 target = this;
            final BoundingBoxType1 leftObject = ((BoundingBoxType1) left);
            final BoundingBoxType1 rightObject = ((BoundingBoxType1) right);
            
            {
            	CoordType lhsPoint;
                lhsPoint = leftObject.getCoord1();
                CoordType rhsPoint;
                rhsPoint = rightObject.getCoord1();
                target.setCoord1(((CoordType) strategy.merge(LocatorUtils.property(leftLocator, "coord1", lhsPoint), LocatorUtils.property(rightLocator, "coord1", rhsPoint), lhsPoint, rhsPoint)));
            }
            
            {
            	CoordType lhsPoint;
                lhsPoint = leftObject.getCoord2();
                CoordType rhsPoint;
                rhsPoint = rightObject.getCoord2();
                target.setCoord2(((CoordType) strategy.merge(LocatorUtils.property(leftLocator, "coord2", lhsPoint), LocatorUtils.property(rightLocator, "coord2", rhsPoint), lhsPoint, rhsPoint)));
            }
            
        }
    }
}
